// Para enlistar el blog
export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL';

// Ver las blog por categoria
export const GET_BLOG_LIST_CATEGORIES_SUCCESS = 'GET_BLOG_LIST_CATEGORIES_SUCCESS';
export const GET_BLOG_LIST_CATEGORIES_FAIL = 'GET_BLOG_LIST_CATEGORIES_FAIL';

// Detallar un blog
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL';

// Buscar un blog
export const GET_SEARCH_BLOG_SUCCESS = 'GET_SEARCH_BLOG_SUCCESS';
export const GET_SEARCH_BLOG_FAIL = 'GET_SEARCH_BLOG_FAIL';

// Post por autor
export const GET_AUTHOR_BLOG_LIST_SUCCESS = 'GET_AUTHOR_BLOG_LIST_SUCCESS';
export const GET_AUTHOR_BLOG_LIST_FAIL = 'GET_AUTHOR_BLOG_LIST_FAIL';